packaging_format = 2

id = "element"
name = "Element"
description.en = "Web client for Matrix"
description.fr = "Client web pour Matrix"

version = "1.11.53~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "Apache-2.0"
website = "https://element.io"
demo = "https://app.element.io/"
admindoc = "https://element.io/help"
code = "https://github.com/vector-im/element-web/"
cpe = "cpe:2.3:a:matrix:element"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "70M"
ram.build = "0M"
ram.runtime = "0M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/element"

    [install.default_home_server]
    ask.en = "Choose a default Matrix server"
    ask.fr = "Choisissez un serveur Matrix par défault"
    type = "string"
    example = "my-own-homeserver.tld"
    default = "matrix.org"

    [install.init_main_permission]
    help.en = "'visitors' permission means that anyone can access the Element application."
    help.fr = "Autoriser les 'Visiteurs' signifie que n'importe qui peut accéder l'application Element."
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/vector-im/element-web/releases/download/v1.11.53/element-v1.11.53.tar.gz"
        sha256 = "d62d5cba98281b5f35d42d03f7850167abd086261d473e27b26b91adc5c8aa9b"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
